// Consider LocalDateTime stable
java.time.LocalDateTime
//  Consider my datalayer stable
// com.datalayer.*
//  Consider my datalayer and all submodules stable
// com.datalayer.**
//  Consider my generic type stable based off it is first type parameter only
// com.example.GenericClass<*,_>
android.content.Intent
com.android.billingclient.api.Purchase
com.android.billingclient.api.ProductDetails
kotlinx.coroutines.flow.StateFlow<*>

// Treat CharSequence | Uri | File as stable
kotlin.CharSequence
android.net.Uri
java.io.File

// Preferences DataStore
com.zs.preferences.Preferences
com.zs.preferences.Key
com.zs.preferences.Key.Key1<*,_>
com.zs.preferences.Key.Key2<*,_>

// core classes
com.zs.core.db.playlists.Playlist
com.zs.core.db.playlists.Playlist.Track
com.zs.core.db.playlists.Playlists
com.zs.core.store.models.Audio
com.zs.core.store.models.Folder
com.zs.core.store.models.Trashed
com.zs.core.store.models.Video
com.zs.core.store.models.Audio.Genre
com.zs.core.store.models.Audio.Artist
com.zs.core.store.models.Audio.Album

// Playback
com.zs.core.playback.NowPlaying
androidx.media3.common.VideoSize
androidx.media3.common.Player
androidx.media3.common.MediaItem
com.zs.core.playback.Remote
com.zs.core.playback.Remote.TrackInfo

// store classes